In [2]:
import numpy as np # importing numpy module.

In [3]:
np.__version__ #numpy version

'1.26.4'

In [25]:
list_new = [1,2,3,4,5] #declaring a list and assigning to numpy
numpy_array_new = np.array(list_new) # declaring as array in numpy
 print(array_new)

IndentationError: unexpected indent (209082723.py, line 3)

In [13]:
#creating 2D array
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [18]:
# creating 3D array

array_3D = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(array_3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [22]:
# dtype

array_dtype_int = np.array([1,2,3], dtype=int)
print(array_dtype_int)

array_dtype_float = np.array([1,2,3], dtype=float)
print(array_dtype_float)

array_dtype_complex = np.array([1,2,3], dtype=complex)
print(array_dtype_complex)

array_dtype_bool = np.array([1,2,4,5,0], dtype=bool)
print(array_dtype_bool)

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]
[ True  True  True  True False]


In [23]:
# example for arange in numpy
numpy_arange = np.arange(7)
numpy_array_new

array([1, 2, 3, 4, 5])

In [26]:
numpy_arange_2 = np.arange(7,2)
numpy_arange_2

array([], dtype=int32)

In [27]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [28]:
np.arange(1,11).reshape(5,2) # prints a 2D matrices

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
np.zeros((4,5)) # printing a 4X5 matrices with float zeros
     

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros([4,5], dtype='int32')
     

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
# np.ones and np.zeros
np.ones((5,5), dtype=float) # prints ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones((5,5), dtype=int) # prints ones as int
     

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.ones((5,5), dtype=int) # prints ones as int
     

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.ones((5,5), dtype=bool) # prints ones as bool

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [36]:
np.arange(1,26).reshape(5,5) # reshape (should be a correct multiples for forming matrix)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
# Another Type --> random()

np.random.random((4,3))

array([[0.42007201, 0.70779547, 0.97559598],
       [0.72248934, 0.48799392, 0.82179546],
       [0.32426553, 0.65752769, 0.42500497],
       [0.75816046, 0.16483512, 0.74006549]])

In [38]:
np.ndarray

numpy.ndarray

In [39]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 16, 19, 16],
       [12, 16, 11, 14],
       [15, 13, 13, 16],
       [12, 17, 11, 16],
       [18, 10, 15, 16]])

In [40]:
b[1:3]
     

array([[12, 16, 11, 14],
       [15, 13, 13, 16]])

In [41]:
b[1, 0]

12

In [42]:
b[1:3]

array([[12, 16, 11, 14],
       [15, 13, 13, 16]])

In [43]:
b[1, 0]

12

In [44]:
b[0:-2]

array([[18, 16, 19, 16],
       [12, 16, 11, 14],
       [15, 13, 13, 16]])

In [45]:

# trying with 10 X 10 matrix

arr2 = np.random.randint(0,100,(10,10))
arr2

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [83, 59, 53, 57, 87, 21, 70,  3, 41, 67],
       [ 8,  0, 99, 97, 80, 44, 50, 72, 71, 13],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [58, 37, 83, 14, 88, 69, 98, 46, 52, 51],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [46]:
print(arr2[::-1])

[[22 86 74 72 32 80 34 25 79 10]
 [19 81 71 81 93 68 61 30 71 79]
 [98 65 72 77 51 86 89 47 81 61]
 [ 1 27  9 77 57 23 78 85 88 61]
 [58 37 83 14 88 69 98 46 52 51]
 [79 75 64 83 33 21 70 42 27 94]
 [58 34 38 41 18 83  7 74 40 99]
 [ 8  0 99 97 80 44 50 72 71 13]
 [83 59 53 57 87 21 70  3 41 67]
 [66 78 53 39 30 89 83 33 94 98]]


In [47]:
print(arr2[::-2])

[[22 86 74 72 32 80 34 25 79 10]
 [98 65 72 77 51 86 89 47 81 61]
 [58 37 83 14 88 69 98 46 52 51]
 [58 34 38 41 18 83  7 74 40 99]
 [83 59 53 57 87 21 70  3 41 67]]


In [48]:

print(arr2[::-3])

[[22 86 74 72 32 80 34 25 79 10]
 [ 1 27  9 77 57 23 78 85 88 61]
 [58 34 38 41 18 83  7 74 40 99]
 [66 78 53 39 30 89 83 33 94 98]]


In [49]:
#arr2[0:10:3]
# This slices rows from index 0 to 9, taking 3rd row
arr2

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [83, 59, 53, 57, 87, 21, 70,  3, 41, 67],
       [ 8,  0, 99, 97, 80, 44, 50, 72, 71, 13],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [58, 37, 83, 14, 88, 69, 98, 46, 52, 51],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [50]:
arr2[0:10:3]

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [51]:
arr2[0:10:4]

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79]])

In [52]:
arr2

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [83, 59, 53, 57, 87, 21, 70,  3, 41, 67],
       [ 8,  0, 99, 97, 80, 44, 50, 72, 71, 13],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [58, 37, 83, 14, 88, 69, 98, 46, 52, 51],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

### Numpy Array Functions

In [53]:
print(arr2.max())

99


In [54]:

print(arr2.min())

0


In [55]:
print(arr2.mean())

58.15


In [56]:
print(arr2.mode())

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [57]:
from numpy import *
a = median(arr2)
a

64.5

In [58]:
arr2

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [83, 59, 53, 57, 87, 21, 70,  3, 41, 67],
       [ 8,  0, 99, 97, 80, 44, 50, 72, 71, 13],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [58, 37, 83, 14, 88, 69, 98, 46, 52, 51],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [59]:
row =5
col = 6

print(arr2[row,col])

98


In [60]:
print(arr2[6,5])
     

23


In [61]:
print(arr2[5:6, 2:3])

[[83]]


In [62]:
arr2[7:10]

array([[98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [63]:
arr2[:,col] # prints the column as blow is the result of column

array([83, 70, 50,  7, 70, 98, 78, 89, 61, 34])

In [64]:
print(row)
print(col)

5
6


In [65]:
print(arr2[row,:])

[58 37 83 14 88 69 98 46 52 51]


In [66]:
print(arr2[:,-1])

[98 67 13 99 94 51 61 61 79 10]


In [67]:
print(arr2[:])

[[66 78 53 39 30 89 83 33 94 98]
 [83 59 53 57 87 21 70  3 41 67]
 [ 8  0 99 97 80 44 50 72 71 13]
 [58 34 38 41 18 83  7 74 40 99]
 [79 75 64 83 33 21 70 42 27 94]
 [58 37 83 14 88 69 98 46 52 51]
 [ 1 27  9 77 57 23 78 85 88 61]
 [98 65 72 77 51 86 89 47 81 61]
 [19 81 71 81 93 68 61 30 71 79]
 [22 86 74 72 32 80 34 25 79 10]]


In [ ]:
Masking:

Masking means applying a condition to a numpy arry to filter/select elements based on True/False values.

In [68]:
arr2 > 50 # This will just set the values greater than 50 to True and 50 and less than to False
     

array([[ True,  True,  True, False, False,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True, False, False,
         True],
       [False, False,  True,  True,  True, False, False,  True,  True,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
         True],
       [ True,  True,  True,  True, False, False,  True, False, False,
         True],
       [ True, False,  True, False,  True,  True,  True, False,  True,
         True],
       [False, False, False,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [False,  True,  True,  True, False,  True, False, False,  True,
        False]])

In [69]:
print(arr2[arr2 > 50]) # this would give the values greater than 50

[66 78 53 89 83 94 98 83 59 53 57 87 70 67 99 97 80 72 71 58 83 74 99 79
 75 64 83 70 94 58 83 88 69 98 52 51 77 57 78 85 88 61 98 65 72 77 51 86
 89 81 61 81 71 81 93 68 61 71 79 86 74 72 80 79]


In [70]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [73]:
arr.reshape(2,3)

NameError: name 'arr' is not defined

In [72]:
arr2[:]

array([[66, 78, 53, 39, 30, 89, 83, 33, 94, 98],
       [83, 59, 53, 57, 87, 21, 70,  3, 41, 67],
       [ 8,  0, 99, 97, 80, 44, 50, 72, 71, 13],
       [58, 34, 38, 41, 18, 83,  7, 74, 40, 99],
       [79, 75, 64, 83, 33, 21, 70, 42, 27, 94],
       [58, 37, 83, 14, 88, 69, 98, 46, 52, 51],
       [ 1, 27,  9, 77, 57, 23, 78, 85, 88, 61],
       [98, 65, 72, 77, 51, 86, 89, 47, 81, 61],
       [19, 81, 71, 81, 93, 68, 61, 30, 71, 79],
       [22, 86, 74, 72, 32, 80, 34, 25, 79, 10]])

In [74]:
arr.reshape(2,3)

NameError: name 'arr' is not defined

## Indexing

In [77]:
mat = np.arange(0,100).reshape(10,10)

In [78]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
row=4
col=5

In [79]:
row

5

In [80]:
col

6

In [81]:
mat[row,col]

56

In [82]:
mat[4,5]

45

In [83]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [86]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [87]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

# Masking

In [90]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
id(mat)

1797445099632

In [92]:

mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [93]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [94]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [95]:
mat[mat==50]

array([50])

In [96]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [97]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [98]:
a4 = mat[mat==50]
a4

array([50])

In [99]:
a1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [100]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Array Creation Functions

In [103]:
import numpy as np

In [104]:
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [105]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [106]:
# Create an array with linearly spaced values
c = np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [107]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [108]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [109]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Functions

In [110]:
# Reshape an array
a1 = np.array([1, 2, 3, 4])
reshaped = np.reshape(a1, (1, 4))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3 4]]


In [111]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [112]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [113]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# Mathematical Functions


In [114]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [115]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [116]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [117]:
print(a1)
print(g)

[1 2 3 4]
[1 2 3 4]


In [118]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [119]:
print(a)
print(a1)

[1 2 3]
[1 2 3 4]


In [127]:
a3 = np.array([1, 2, 3])
 dot_product = np.dot(a1, a)  # Dot product of a and g
    print("Dot product of a1 and a:", dot_product)

IndentationError: unexpected indent (1854403749.py, line 2)

# Statistical Functions

In [122]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [123]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [125]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [128]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# Linear Algebra Functions

In [129]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [130]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [131]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Random Sampling Functions

In [132]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)


Random values: [0.79631076 0.0295295  0.55129023]


In [133]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [134]:
# Generate random integers
rand_ints = np.random.randint(10, 20, size=8)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [13 17 19 13 15 12 14 17]


In [135]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(1, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [6 1 4 4 8]


# Boolean Logical Functions

In [136]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [137]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [139]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)


All elements True: False


In [140]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


# Set Operations

In [141]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [142]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Array Attribute Functions

In [144]:
#Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


# Other Functions

In [145]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [146]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [147]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
